Implement lbaasv1.LoadBalancer resource
anexia-it/terraform-provider-anxcloud pull request #107
Opened 2022-07-13 07:31 UTC by marioreggiori

### Description

This PR implements the LBaaS LoadBalancer API resource as a Terraform resource.

### Checklist

* [ ] added release notes to `Unreleased` section in [CHANGELOG.md](CHANGELOG.md), if user facing change

### References

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

2022-07-18 12:06 UTC, LittleFox94 requested changes
Mostly fine, only small comments :)

2022-07-18 12:06 UTC, LittleFox94 commented on CHANGELOG.md
> +* resource/anxcloud_lbaas_loadbalancer: implemented resource (#107, @marioreggiori)
"resource/anxcloud_lbaas_loadbalancer: add a first LBaaS resource"

2022-07-18 12:06 UTC, LittleFox94 commented on examples/resources/anxcloud_lbaas_loadbalancer/resource.tf
> +  ip_address = "192.0.2.1"
we should maybe add some docs how to create the LoadBalancer - at least noting that "Just creating a LoadBalancer resource will sadly not give you a functional LoadBalancer, only make an existing one configurable via Engine"

2022-07-18 12:06 UTC, LittleFox94 commented on anxcloud/schema_lbaas.go
> +			Description: "LoadBalancer IP address.",
something like "Address of the Engine management API of the LoadBalancer" is probably better, also, this does not have to be an IP address as far as I'm aware, but could also be a DNS name

2022-07-18 12:06 UTC, LittleFox94 commented on anxcloud/schema_lbaas.go
> +func schemaLBaaSLoadbalancer() map[string]*schema.Schema {
we should probably stick to one writing style:
* Load**b**alancer
* Load**B**alancer - I prefer this one

2022-07-18 12:06 UTC, LittleFox94 commented on anxcloud/schema_lbaas.go
> +			Description: "LoadBalancer IP address.",
then again "ip_address" matches the API name of that attribute, so fine with that

2022-07-18 12:06 UTC, LittleFox94 commented on anxcloud/resource_lbaas_loadbalancer.go
> +			Delete: schema.DefaultTimeout(5 * time.Minute),
we don't need that high timeout values, let's go with 30s for each except delete (in case it ever learns recursive deletion of resources)?

2022-07-22 16:48 UTC, LittleFox94 submitted a review, later dismissed

2022-07-25 06:59 UTC, LittleFox94 approved these changes

2022-08-04 11:37 UTC, marioreggiori commented
@LittleFox94 I did a rebase and configured the resource test to also run parallel (#102)

2022-08-04 11:40 UTC, LittleFox94 approved these changes

2022-08-04 11:41 UTC, merged