vlan vm provisioning flakiness
anexia-it/terraform-provider-anxcloud pull request #71
Opened 2021-11-24 16:53 UTC by kstiehl

### Description

### Acceptance tests
- [x] Have you added an acceptance test for the functionality being added?
- [x] Have you run the acceptance tests on this branch?

Output from acceptance testing:

### Release Note
Release note for [CHANGELOG](https://github.com/anexia-it/terraform-provider-anxcloud/blob/master/CHANGELOG.md):

```release-note
* resource/vlan - remove a bug where updating a VLAN leads to `vm_provisioning` flakiness.
```

### References

* **SYSENG-415**

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

2021-11-30 14:37 UTC, LittleFox94 requested changes
I'm not happy with this fixing two different things, please pull the test fix for vsphere template lookup out of this into it's own PR to be merged first

2021-11-30 16:51 UTC, kstiehl commented
Always using the latest template has been moved to #73 and the code has been removed from this PR

2021-12-08 09:13 UTC, LittleFox94 reviewed
Also the changelog is probably for `resource/anxcloud_vlan`? The whole project is about anxcloud resources, but having this prefix was spec'd by you in your example in #72 

Please squash your commits in a reasonable way, I'd like not to have those kinda chaotic "merge chaos" commits in history and am not if squashing all into a single commit is the best we can do here (though, judging from the number of lines changes, probably is).

2021-12-08 09:13 UTC, LittleFox94 commented on anxcloud/resource_vlan_test.go
> -				Config: testAccCheckAnxCloudVLAN(resourceName, locationID, customerDescription, false),
testing for `VMProvisioning=false` is not done in any test anymore, is this intentional?

2021-12-08 09:15 UTC, LittleFox94 commented
Oh and update branch please, when you are squashing anyway ^^

2022-02-23 13:13 UTC, LittleFox94 approved these changes
lgtm

2022-02-23 13:13 UTC, merged