Implements anxcloud_core_location data-source
anexia-it/terraform-provider-anxcloud pull request #84
Opened 2022-05-02 09:10 UTC by marioreggiori

### Description

Implements `anxcloud_core_location` data-source. Allows Location to be fetched by it's human-readable `code`-identifier.

### Acceptance tests
- [ ] Have you added an acceptance test for the functionality being added?
- [ ] Have you run the acceptance tests on this branch?

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'
...
```

### Release Note
Release note for [CHANGELOG](https://github.com/anexia-it/terraform-provider-anxcloud/blob/master/CHANGELOG.md):

```release-note
* core/v1/Location - implement singular anxcloud_core_location data-source (matched with `code` argument)
* upgrade go-anxcloud dependency to 0.4.2
```

### References

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

2022-05-02 09:47 UTC, marioreggiori commented
Failing test shouldn't be related.

2022-05-02 14:46 UTC, LittleFox94 requested changes

2022-05-02 14:46 UTC, LittleFox94 commented on anxcloud/data_source_core_location.go
> +	if err := a.List(ctx, searchLocation, api.ObjectChannel(&channel)); err != nil {
when `List`ing with object channels, you always have to either read until the channel is closed or use a context you cancel when you found your object - without that, you'll leak a goroutine.

https://pkg.go.dev/go.anx.io/go-anxcloud@v0.4.2/pkg/api#ObjectChannel

2022-05-03 12:02 UTC, LittleFox94 approved these changes

2022-05-03 12:02 UTC, LittleFox94 commented on anxcloud/data_source_core_location.go
> +	listCTX, cancel := context.WithCancel(ctx)
can't explain it, but `listCTX` looks odd to me - maybe just replace `ctx` with your new context?

Up to you, not preventing a merge :)

2022-05-03 12:20 UTC, merged